### ISSUE TITLE
Warrior cannot be started on Windows

### ISSUE THREAD

**Issue by habi** [ArchiveTeam/warrior-code2#8]
I'm running the archiveteam warrior (1) on VirtualBox (2) on Windows (3).
Whenever I want to start up the appliance, I only get to `Loading initial ramdisk`, then the appliance crashes.

A copy of the log file can be found [here on pastebin.com](http://pastebin.com/raw/6RzxVvsY).
What can I do to run the appliance on Windows?

(1): archiveteam-warrior-v2-20121008.ova
(2): Version 5.1.10 r112026 (Qt5.6.2)
(3): Windows 7 Enterprise, Service Pack 1, 64 bit

**Comment by chfoo** [comment]
Have you changed any of the appliance settings? I see `00:00:01.669560 WARNING! 64-bit guest type selected but the host CPU does NOT support HW virtualization.`. Maybe change the appliance type from 64-bit to 32-bit or vice versa.

Also I see `00:00:01.789130 HM: HMR3Init: Falling back to raw-mode: VT-x is disabled in the BIOS for all CPU modes`. I'm not sure, but maybe check to see if any virtualization options is enabled in BIOS too. 

If doing that doesn't help, try using an older version of VirtualBox like 5.0. It might be a new VirtualBox bug.

**Comment by habi** [comment]
- I didn't change any settings in the appliance, it's a fresh, unedited download from the archiveteam website.
- I can't change the appliance type to anything else than 32bit systems, as seen below (the rest of the entries not shown are all 32bit systems).
![clipboard01](https://cloud.githubusercontent.com/assets/1651235/21256216/57f997e0-c371-11e6-97c9-64242ab89c82.png)
- Due to other people being logged in to my machine (workstation, shared) I cannot reboot to look for the changes in the BIOS.
- I've downloaded VirtualBox Version 5.0.30 r112061, but this version also fails to start the appliance, with the error below.
![clipboard02](https://cloud.githubusercontent.com/assets/1651235/21256328/eeceecf6-c371-11e6-91d2-14abf8020cf0.png)

**Comment by chfoo** [comment]
I'm not sure what the problem could be. Maybe try posting on the VirtualBox forums for help? If you find out the problem or someone else knows, please feel free to let us now.

**Comment by habi** [comment]
After posting in the VirtualBox forum I was pointed to this entry there: https://forums.virtualbox.org/viewtopic.php?f=1&t=62339

I needed to enable `VT-x` in my BIOS, now everything works as expected.
