### ISSUE TITLE
Configuring network settings?

### ISSUE THREAD

**Issue by khromov** [ArchiveTeam/warrior-code2#9]
I need to set custom network settings for my Warrior (static IP / custom gateway). How can I do this?

**Comment by chfoo** [comment]
I'm not sure what you mean exactly. Are you using the Virtualbox appliance or running the code standalone? Are you using Windows, macOS, or Linux? What have you set up in your network so far?

**Comment by khromov** [comment]
@chfoo After finding the root login, I was able to edit `/etc/network/interfaces` and add the static IP as follows:

```
#auto eth0 <-- comment out these
#iface eth0 inet dhcp <-- comment out these

# Add this
auto eth0
iface eth0 inet static
    address 192.168.2.123
    netmask 255.255.255.0
    gateway 192.168.2.2
    dns-nameservers 192.168.2.2
```

In `/etc/resolv.conf`, you might also need to replace your DNS server IP. 

Thanks for the quick assistance. :-)
